# Generated by Django 3.2.23 on 2024-08-24 19:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('img', models.FileField(upload_to='Thumbnail')),
                ('title', models.CharField(max_length=70)),
                ('desc', models.TextField(max_length=500, null=True)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
