# Generated by Django 3.2.25 on 2024-09-19 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_addcart_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='id',
            new_name='order_id',
        ),
    ]
