# Generated by Django 3.2.25 on 2024-09-21 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20240921_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='addcart',
            name='total_price_item',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
