# Generated by Django 3.2.25 on 2024-09-21 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20240921_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addcart',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='addcart',
            name='total_price_item',
        ),
    ]
