# Generated by Django 3.2.25 on 2024-09-23 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20240921_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='addcart',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(to='app.addcart'),
        ),
    ]
