# Generated by Django 3.2.25 on 2024-09-23 15:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20240923_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcart',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
