# Generated by Django 3.2.25 on 2024-09-23 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_order_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
    ]
